### ISSUE TITLE
Firebug is the active context

### ISSUE THREAD

**Issue by lordi** [bard/mozrepl#45]
Hi,

when I opened Firebug as a separate window and connect to the repl, Firebug will be the active context. How can I skip the Firebug context?

    repl> repl.whereAmI();
    [object ChromeWindow] - Document title: "Firebug - inaktiv für die aktuelle Webseite"

**Comment by rpl** [comment]
@lordi you can restrict the context selected by mozrepl with the "-repl-context WINDOWTYPE" command line option, e.g. the follows command line start mozrepl and restrict the selected context to Firefox browser windows:

```
firefox -repl-context navigator:browser
```
