### ISSUE TITLE
window.document.URL returning browser URL

### ISSUE THREAD

**Issue by erjoalgo** [bard/mozrepl#64]
```
repl> window.document.title
"Tutorial · bard/mozrepl Wiki - Iceweasel"
repl> window.document.URL
"chrome://browser/content/browser.xul"
repl> 
```
Shouldn't this be
https://github.com/bard/mozrepl/wiki/Tutorial 
?

**Comment by pyhedgehog** [comment]
This is intended - `window` object corresponds to window itself - chrome window.
Use `context` for context window of currently selected tab.

**Comment by erjoalgo** [comment]
Where is this `context` documentation? Can you please tell me how to get the URL of the current window?

**Comment by pyhedgehog** [comment]
Sorry, I've made a tipo - `content`, instead of `context`.
Documented (as always) on MDN: [`content`](https://developer.mozilla.org/en-US/docs/Web/API/Window/content).
So to get url of browser content of selected tab of topmost browser window, you should write:
```JavaScript
repl> content.document.location.href
"https://github.com/bard/mozrepl/issues/64#issuecomment-137261813"
```

**Comment by erjoalgo** [comment]
thanks,  this worked well
