### ISSUE TITLE
MozRepl add on does not work with FF55

### ISSUE THREAD

**Issue by rappazf** [bard/mozrepl#68]
Tested with a perl script using the module WWW::Mechanize::Firefox. The script which works with FF54 does not work with FF55.

**Comment by balta2ar** [comment]
Same here. It's surprising, though, that it's not working, because according to their notice (https://support.mozilla.org/en-US/kb/firefox-add-technology-modernizing), things should break on FF27 (November 2017). @bard Any ideas?

**Comment by danger89** [comment]
Same!

I can't use `document.hasFocus()`, nor `window.location.href` nor `document.readyState`. These requests won't return anything anymore :(.

While my application did work with FF54.

**Comment by bard** [comment]
Sorry to be the bringer of bad news, but I haven't worked on MozRepl for a long time (as you can see from the home page, the project is officially orphaned), and any possible fix would be short-lived anyway, since Mozilla is retiring XPCOM support (which MozRepl depends on) in November 2017.

**Comment by danger89** [comment]
_**Ow no!!**_
I just created a great application which costs me more than 90 hours of work, which now uses MozRepl to interact with Firefox. 😒
